// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Log.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Messages {
  public static partial class LogService
  {
    static readonly string __ServiceName = "LogService";

    static readonly grpc::Marshaller<global::Messages.LogRequest> __Marshaller_LogRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Messages.LogRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Messages.LogResponse> __Marshaller_LogResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Messages.LogResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Messages.GetLogRequest> __Marshaller_GetLogRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Messages.GetLogRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Messages.GetLogResponse> __Marshaller_GetLogResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Messages.GetLogResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Messages.LogRequest, global::Messages.LogResponse> __Method_Log = new grpc::Method<global::Messages.LogRequest, global::Messages.LogResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Log",
        __Marshaller_LogRequest,
        __Marshaller_LogResponse);

    static readonly grpc::Method<global::Messages.GetLogRequest, global::Messages.GetLogResponse> __Method_GetLog = new grpc::Method<global::Messages.GetLogRequest, global::Messages.GetLogResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetLog",
        __Marshaller_GetLogRequest,
        __Marshaller_GetLogResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Messages.LogReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of LogService</summary>
    [grpc::BindServiceMethod(typeof(LogService), "BindService")]
    public abstract partial class LogServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Messages.LogResponse> Log(global::Messages.LogRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Messages.GetLogResponse> GetLog(global::Messages.GetLogRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for LogService</summary>
    public partial class LogServiceClient : grpc::ClientBase<LogServiceClient>
    {
      /// <summary>Creates a new client for LogService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public LogServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for LogService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public LogServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected LogServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected LogServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Messages.LogResponse Log(global::Messages.LogRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Log(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Messages.LogResponse Log(global::Messages.LogRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Log, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Messages.LogResponse> LogAsync(global::Messages.LogRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LogAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Messages.LogResponse> LogAsync(global::Messages.LogRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Log, null, options, request);
      }
      public virtual global::Messages.GetLogResponse GetLog(global::Messages.GetLogRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetLog(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Messages.GetLogResponse GetLog(global::Messages.GetLogRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetLog, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Messages.GetLogResponse> GetLogAsync(global::Messages.GetLogRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetLogAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Messages.GetLogResponse> GetLogAsync(global::Messages.GetLogRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetLog, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override LogServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new LogServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(LogServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Log, serviceImpl.Log)
          .AddMethod(__Method_GetLog, serviceImpl.GetLog).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, LogServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Log, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Messages.LogRequest, global::Messages.LogResponse>(serviceImpl.Log));
      serviceBinder.AddMethod(__Method_GetLog, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Messages.GetLogRequest, global::Messages.GetLogResponse>(serviceImpl.GetLog));
    }

  }
}
#endregion
